version: '3'

services:

  loading-system:
    image: hunk/trekbit-loading-system:lates
    container_name: trekbit-loading-system
    environment:
      - TZ=Europe/Moscow
    volumes:
      - "./db:/app/db"
      - "./log:/app/log"
    ports:
      - 5000:5000
    restart: always
  
  syslog-ng:
    image: ghcr.io/linuxserver/syslog-ng
    container_name: syslog-ng
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Moscow
    volumes:
      - ./syslog-ng:/config
      - ./log:/var/log
    ports:
      - 514:514/udp
      - 601:6601/tcp
      - 6514:6514/tcp
    restart: unless-stopped
