version: '3'

services:

  loading-system:
    image: hunk/automatic_pump-room:latest
    container_name: automatic_pump-room
    environment:
      - TZ=Europe/Moscow
    volumes:
      - "./db:/app/db"
      - "./log:/app/log"
        #network_mode: host
    ports:
      - 5001:5001
    restart: always
  
  syslog-ng:
    image: ghcr.io/linuxserver/syslog-ng
    container_name: syslog-ng
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Moscow
    volumes:
      - ./syslog-ng:/config
      - ./log:/var/log
        #network_mode: host
    ports:
      - 514:514/udp
      - 601:6601/tcp
      - 6514:6514/tcp
    restart: unless-stopped
